### ISSUE TITLE
Replacement model for BTS141 FET?

### ISSUE THREAD

**Issue by DidierA** [arachnidlabs/reload-pro#101]
Hi,
I have broken the legs of the BTS141 FET. I searched for replacement units, but it seems this model is not made anymore. Is there another model that I can replace it with?

**Comment by udif** [comment]
https://octopart.com/search?q=BTS141&currency=USD&specs=0

Newark seems to have some in stock, with minimum order quantity (MOQ) of 1.

**Comment by DidierA** [comment]
Thank you, I finally found one in a french shop online, easier and faster for my location :)
