### ISSUE TITLE
Display of ohms when current set to zero

### ISSUE THREAD

**Issue by raivisr** [arachnidlabs/reload-pro#88]
Sorry for blurrycam, but this is how it looks if display is set tho show ohms and current is set to zero. Probably because of noise in current measurement it jumps between no resistance and something small.
![20150326_203613](https://cloud.githubusercontent.com/assets/1376160/6882639/25bf4eee-d595-11e4-8b50-0e9eae5fc94c.png)

**Comment by knarfS** [comment]
I already posted nearly the same bug plus some others related to the Ohms readout. See #72

**Comment by raivisr** [comment]
Duplicate of #72
