### ISSUE TITLE
Left Hand Voltage Display garbage

### ISSUE THREAD

**Issue by nealzip** [arachnidlabs/reload-pro#89]
Running 1.10 code and right hand voltage having display corruption sometimes. 

Display does correct it self given enough time. Maybe corrupt after adjusting menu???

**Comment by Arachnid** [comment]
What readouts are you selecting for the small displays when this happens?

**Comment by nealzip** [comment]
I had Voltage on Left and Total Current on the right AMPs on top.
![img_3341](https://cloud.githubusercontent.com/assets/2280674/7117514/0f80c0fc-e1c7-11e4-9bc0-a59f92d58d45.jpg)

**Comment by Arachnid** [comment]
Duplicate of #17 .
