### ISSUE TITLE
New serial command output

### ISSUE THREAD

**Issue by knarfS** [arachnidlabs/reload-pro#91]
A serial command to request the actual output state is missing.

I have created a patch to solve that issue and some other issues with the serial communication.
But I'm not able to upload my diff file here... Can I send my diff to your notdot e-amil address, Nick?

**Comment by Arachnid** [comment]
Thanks for the contribution! It would be best if you could use Github's fork-and-pull-request process: https://help.github.com/articles/using-pull-requests/

**Comment by knarfS** [comment]
Just created a fork and a pull request :)
