### ISSUE TITLE
Low Flash Space

### ISSUE THREAD

**Issue by Ralim** [arachnidlabs/reload-pro#95]
Hi,
As I'm sure that you are aware, there is very very little flash space left in the MCU.
I have started adding code for a simple (but hopefully useful) measurement for battery internal resistance.

I'm wondering if you have any ideas at the moment of where to attack to gain extra room to fit this ?
Currently, I have disabled the startup splash screen in order to be able to test the method.

Open to any ideas?
If not I could go for a trawl to try and clean up and gain some room...

Thanks,
Ralim

**Comment by Arachnid** [comment]
I'm not aware of any places we can easily save space, though there doubtless are some.

For debugging, I generally switch to the debug build (which is larger) but disable the splash screen - so the end result is about the same. I'd rather not disable the splash screen on the production firmware, if possible.
