### ISSUE TITLE
Adding serial command

### ISSUE THREAD

**Issue by Ralim** [arachnidlabs/reload-pro#97]
Hi,
I'm looking to add a new serial command to allow clearing the totals for amp hours and watt hours.
Is there any chance of adding an extra command?

Looking at the comment `/* maximum key range = 13, duplicates = 0 */` [here](https://github.com/arachnidlabs/reload-pro/blob/master/firmware/Reload%20Pro.cydsn/commands.h#L64)

It looks like your using a neat way to resolve the commands to functions... Is there a link to a explanation of this anywhere?

Thanks :)

**Comment by Arachnid** [comment]
This is a perfect hash, generated by a tool called gperf. Command line is in a comment [up top](https://github.com/arachnidlabs/reload-pro/blob/master/firmware/Reload%20Pro.cydsn/commands.h#L2).
